### PR TITLE
Fix M1 support

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #37

### CODE REVIEW

**Comment by geoand** [comment]
@maxandersen can you try this please?

**Comment by maxandersen** [comment]
it does seem to download the right binary but if I `rm ~/.quarkus` to test again I get this error:

```
2022-12-28 10:46:14,333 WARN  [io.qua.dep.dev.IsolatedDevModeMain] (main) Unable to invoke 'afterFirstStart' of class io.quarkiverse.ngrok.deployment.NgrokDevModeListener: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /Users/manderse/.quarkus/ngrok
	at io.quarkiverse.ngrok.deployment.NgrokDevModeListener.afterFirstStart(NgrokDevModeListener.java:44)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:149)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IDEDevModeMain.accept(IDEDevModeMain.java:71)
	at io.quarkus.deployment.dev.IDEDevModeMain.accept(IDEDevModeMain.java:28)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.bootstrap.jbang.JBangDevModeLauncherImpl.main(JBangDevModeLauncherImpl.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.launcher.JBangDevModeLauncher.main(JBangDevModeLauncher.java:32)
Caused by: java.nio.file.NoSuchFileException: /Users/manderse/.quarkus/ngrok
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at io.quarkiverse.ngrok.deployment.NgrokDevModeListener.startNgrokIfNecessary(NgrokDevModeListener.java:69)
	at io.quarkiverse.ngrok.deployment.NgrokDevModeListener.afterFirstStart(NgrokDevModeListener.java:42)
	... 12 more
```

**Comment by maxandersen** [comment]
I have to do `mkdir ~/.quarkus/ngrok` then it tries download it again.

Probably old bug - seems it assumes `~/.quarkus` must exist first.

**Comment by maxandersen** [comment]
whoops - didn't realize I was pushingto wrong branch. but now it also create parent directories.

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
