### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I will handle merging this right after i release.

**Comment by gastaldi** [comment]
@all-contributors add @geoand and @melloware for code and maintenance

**Comment by gastaldi** [comment]
@all-contributors add @melloware for code and maintenance

**Comment by gastaldi** [comment]
@all-contributors add @melloware for code and maintenance

**Pull request merged**
